import type { Place } from '../types.js';
import { pickByDay } from '../util/time.js';

/**
 * 50 curated, real Bangkok places worth visiting — temples, palaces, museums,
 * parks, markets, riverside spots, landmarks and a couple of day-trip parks.
 * Restaurants are intentionally excluded. The morning post walks through these
 * one per day, in array order, cycling back to the start after 50 days.
 *
 * Each entry carries a Korean hook (blurbKo), a "what you can see" line (seeKo),
 * and a transit-first "how to get there" line (goKo). Coordinates are approximate
 * site centroids. Verified 2026-05-29 against current transit and opening status.
 */
export const PLACES: readonly Place[] = [
  {
    id: 'grand-palace', nameKo: '왕궁', nameEn: 'The Grand Palace', nameTh: 'พระบรมมหาราชวัง',
    area: '라따나꼬신(올드타운)',
    blurbKo: '방콕에 처음 왔다면 여기부터. 왕실의 화려함이 응축된 곳이에요.',
    seeKo: '에메랄드 불상을 모신 왓 프라깨우, 황금 체디, 짜끄리 마하 쁘라삿 궁전',
    goKo: 'MRT 사남차이역 도보, 또는 짜오프라야 보트 따창 선착장(N9). 긴바지·어깨 가리는 옷 필수',
    lat: 13.75, lon: 100.4915, tag: 'GrandPalace',
  },
  {
    id: 'wat-pho', nameKo: '왓 포(와불사원)', nameEn: 'Wat Pho', nameTh: 'วัดโพธิ์',
    area: '라따나꼬신(올드타운)',
    blurbKo: '길이 46m 황금 와불이 누워 있는, 태국 마사지의 본산.',
    seeKo: '거대한 황금 와불, 발바닥 자개 장식, 수백 개의 불탑(체디), 전통 마사지 학교',
    goKo: '왕궁에서 도보 10분. 따띠엔 선착장(N8) 또는 MRT 사남차이역',
    lat: 13.7465, lon: 100.4927, tag: 'WatPho',
  },
  {
    id: 'wat-arun', nameKo: '왓 아룬(새벽사원)', nameEn: 'Wat Arun', nameTh: 'วัดอรุณ',
    area: '톤부리 강변',
    blurbKo: '강 건너에서 빛나는 도자기 탑. 방콕을 상징하는 실루엣이에요.',
    seeKo: '도자기 조각으로 뒤덮인 거대한 중앙 쁘랑, 올라가서 보는 강 전망과 일몰',
    goKo: '따띠엔 선착장에서 크로스리버 페리로 강 건너 바로',
    lat: 13.7437, lon: 100.4889, tag: 'WatArun',
  },
  {
    id: 'golden-mount', nameKo: '왓 사켓(황금산)', nameEn: 'Wat Saket (Golden Mount)', nameTh: 'วัดสระเกศ',
    area: '올드타운',
    blurbKo: '나선 계단을 올라 만나는 도심 최고의 360도 전망대.',
    seeKo: '인공 언덕 위 황금 체디, 계단을 감싼 종(鐘)들, 올드타운 파노라마',
    goKo: 'MRT 삼욧역에서 도보 약 15분',
    lat: 13.7536, lon: 100.5066, tag: 'GoldenMount',
  },
  {
    id: 'wat-benchamabophit', nameKo: '왓 벤짜마보핏(대리석 사원)', nameEn: 'Wat Benchamabophit', nameTh: 'วัดเบญจมบพิตร',
    area: '두싯',
    blurbKo: '이탈리아 대리석으로 지은 새하얀 사원. 옛 5밧 동전의 주인공.',
    seeKo: '카라라 대리석 본당, 좌우 대칭의 우아한 회랑, 청동 불상 컬렉션',
    goKo: '두싯 지역, 택시 또는 버스가 편해요(인근 역 도보 거리 멀어요)',
    lat: 13.7669, lon: 100.5142, tag: 'MarbleTemple',
  },
  {
    id: 'wat-traimit', nameKo: '왓 뜨라이밋(황금불)', nameEn: 'Wat Traimit (Golden Buddha)', nameTh: 'วัดไตรมิตร',
    area: '차이나타운',
    blurbKo: '5.5톤짜리 순금 불상이 우연히 발견된 곳.',
    seeKo: '세계 최대 순금 좌불, 차이나타운 역사 전시관',
    goKo: 'MRT 후아람퐁역에서 도보 약 5분, 차이나타운 초입',
    lat: 13.7382, lon: 100.5138, tag: 'GoldenBuddha',
  },
  {
    id: 'wat-suthat', nameKo: '왓 수탓 & 싸오칭차', nameEn: 'Wat Suthat & Giant Swing', nameTh: 'วัดสุทัศน์',
    area: '올드타운',
    blurbKo: '거대한 붉은 그네가 지키는, 방콕에서 가장 고요한 대사원 중 하나.',
    seeKo: '높이 솟은 붉은 자이언트 스윙, 정교한 벽화로 채운 본당',
    goKo: 'MRT 삼욧역에서 도보 약 10분',
    lat: 13.7515, lon: 100.501, tag: 'WatSuthat',
  },
  {
    id: 'loha-prasat', nameKo: '로하 쁘라삿(금속 성)', nameEn: 'Loha Prasat (Wat Ratchanatdaram)', nameTh: 'โลหะปราสาท',
    area: '올드타운',
    blurbKo: '세계에 몇 남지 않은 금속 첨탑 사원. 미로 같은 내부가 매력.',
    seeKo: '금속으로 된 뾰족탑들, 나선 계단으로 오르는 꼭대기 전망',
    goKo: '왓 사켓·민주기념탑 인근, MRT 삼욧역 도보 또는 택시',
    lat: 13.7546, lon: 100.5046, tag: 'LohaPrasat',
  },
  {
    id: 'wat-mangkon', nameKo: '왓 망꼰(차이나타운 사원)', nameEn: 'Wat Mangkon Kamalawat', nameTh: 'วัดมังกรกมลาวาส',
    area: '차이나타운',
    blurbKo: '향 연기 자욱한 차이나타운의 중심 중국식 사원.',
    seeKo: '용 장식의 화려한 지붕, 도교·불교가 섞인 제단, 명절 풍경',
    goKo: 'MRT 왓망꼰역 1번 출구에서 도보 약 5분',
    lat: 13.744, lon: 100.51, tag: 'WatMangkon',
  },
  {
    id: 'wat-paknam', nameKo: '왓 빠끄남', nameEn: 'Wat Paknam Phasi Charoen', nameTh: 'วัดปากน้ำภาษีเจริญ',
    area: '톤부리(파시짜런)',
    blurbKo: '천장 가득 에메랄드빛 유리탑으로 SNS에서 화제가 된 사원.',
    seeKo: '초록 유리 체디와 우주를 닮은 천장화, 거대한 황금 불상',
    goKo: 'MRT 방파이역에서 도보 또는 짧은 택시',
    lat: 13.7167, lon: 100.4639, tag: 'WatPaknam',
  },
  {
    id: 'wat-ratchabophit', nameKo: '왓 랏차보핏', nameEn: 'Wat Ratchabophit', nameTh: 'วัดราชบพิธ',
    area: '올드타운',
    blurbKo: '태국 양식과 유럽 양식이 한 건물에 섞인 독특한 왕실 사원.',
    seeKo: '유럽풍 스테인드글라스가 들어간 본당, 화려한 도자기 외벽',
    goKo: 'MRT 삼욧역에서 도보 약 10분',
    lat: 13.7497, lon: 100.4969, tag: 'WatRatchabophit',
  },
  {
    id: 'wat-intharawihan', nameKo: '왓 인타라위한', nameEn: 'Wat Intharawihan', nameTh: 'วัดอินทรวิหาร',
    area: '방람푸',
    blurbKo: '높이 32m의 거대한 황금 입불상이 동네를 굽어보는 곳.',
    seeKo: '하늘을 향해 선 거대 입불상, 조용한 동네 사원 분위기',
    goKo: '카오산 로드 인근, 택시 또는 도보',
    lat: 13.77, lon: 100.504, tag: 'WatIntharawihan',
  },
  {
    id: 'erawan-shrine', nameKo: '에라완 사당', nameEn: 'Erawan Shrine', nameTh: 'ศาลท้าวมหาพรหม',
    area: '라차쁘라송',
    blurbKo: '쇼핑가 한복판, 소원을 비는 사람들로 늘 붐비는 4면 브라흐마 사당.',
    seeKo: '네 얼굴의 브라흐마 신상, 소원 성취 답례로 펼쳐지는 전통 무용',
    goKo: 'BTS 칫롬역에서 도보 약 3분, 센트럴월드 맞은편',
    lat: 13.7443, lon: 100.5404, tag: 'ErawanShrine',
  },
  {
    id: 'jim-thompson', nameKo: '짐 톰슨 하우스', nameEn: 'Jim Thompson House', nameTh: 'บ้านจิม ทอมป์สัน',
    area: '빠툼완',
    blurbKo: '태국 실크를 세계에 알린 미국인의 전통 가옥 박물관.',
    seeKo: '티크 목조 전통 가옥, 아시아 미술 컬렉션, 푸른 정원',
    goKo: 'BTS 내셔널스타디움역 1번 출구에서 도보 약 5분',
    lat: 13.7491, lon: 100.5285, tag: 'JimThompson',
  },
  {
    id: 'national-museum', nameKo: '방콕 국립박물관', nameEn: 'Bangkok National Museum', nameTh: 'พิพิธภัณฑสถานแห่งชาติ พระนคร',
    area: '라따나꼬신(올드타운)',
    blurbKo: '동남아 최대급 국립박물관. 태국 역사를 한 번에 훑어요.',
    seeKo: '선사시대부터 라따나꼬신까지의 유물, 왕실 장례용 마차',
    goKo: '왕궁 인근, 따창 선착장 또는 택시',
    lat: 13.7574, lon: 100.4922, tag: 'NationalMuseum',
  },
  {
    id: 'museum-siam', nameKo: '뮤지엄 시암', nameEn: 'Museum Siam', nameTh: 'มิวเซียมสยาม',
    area: '라따나꼬신(올드타운)',
    blurbKo: '"태국인이란 무엇인가"를 체험형으로 풀어낸 현대적 박물관.',
    seeKo: '인터랙티브 전시, 태국 정체성을 다룬 재치 있는 연출',
    goKo: 'MRT 사남차이역 1번 출구에서 도보 약 3분',
    lat: 13.7437, lon: 100.4942, tag: 'MuseumSiam',
  },
  {
    id: 'bacc', nameKo: '방콕 예술문화센터(BACC)', nameEn: 'Bangkok Art and Culture Centre', nameTh: 'หอศิลปวัฒนธรรมแห่งกรุงเทพมหานคร',
    area: '빠툼완',
    blurbKo: '나선형 흰 건물 속 무료 현대미술 전시 공간.',
    seeKo: '회전하는 전시 갤러리, 독립 서점·카페·디자인 숍',
    goKo: 'BTS 내셔널스타디움역 3번 출구와 구름다리로 직결',
    lat: 13.7466, lon: 100.5302, tag: 'BACC',
  },
  {
    id: 'moca', nameKo: '방콕 현대미술관(MOCA)', nameEn: 'MOCA Bangkok', nameTh: 'พิพิธภัณฑ์ศิลปะไทยร่วมสมัย',
    area: '짜뚜짝 북부',
    blurbKo: '태국 현대미술을 집대성한 5층짜리 개인 미술관.',
    seeKo: '층마다 이어지는 방대한 회화 컬렉션, 사진 명소인 건축 자체',
    goKo: '시내에서 다소 멀어요. 택시 또는 차량 추천',
    lat: 13.8519, lon: 100.5623, tag: 'MOCA',
  },
  {
    id: 'suan-pakkad', nameKo: '수안 파깟 궁전', nameEn: 'Suan Pakkad Palace', nameTh: 'วังสวนผักกาด',
    area: '빠야타이',
    blurbKo: '도심 속 숨은 전통 가옥 정원. 한적하게 옛 태국을 만나요.',
    seeKo: '여러 채의 티크 전통 가옥, 금박 래커 정자(Lacquer Pavilion)',
    goKo: 'BTS 파야타이역에서 도보 약 5분',
    lat: 13.756, lon: 100.539, tag: 'SuanPakkad',
  },
  {
    id: 'erawan-museum', nameKo: '에라완 박물관(머리 셋 코끼리)', nameEn: 'The Erawan Museum', nameTh: 'พิพิธภัณฑ์ช้างเอราวัณ',
    area: '사뭇쁘라깐',
    blurbKo: '머리가 셋 달린 거대한 청동 코끼리상이 통째로 박물관인 곳.',
    seeKo: '거대 3두 코끼리 조각, 신화를 형상화한 화려한 내부와 정원',
    goKo: 'BTS 창 에라완역에서 도보 또는 짧은 택시',
    lat: 13.6283, lon: 100.5889, tag: 'ErawanMuseum',
  },
  {
    id: 'ancient-city', nameKo: '무앙 보란(고대 도시)', nameEn: 'Ancient City (Muang Boran)', nameTh: 'เมืองโบราณ',
    area: '사뭇쁘라깐',
    blurbKo: '태국 전역의 명소를 축소 재현한 거대한 야외 박물관. 자전거 한 바퀴가 제맛.',
    seeKo: '태국 모양으로 배치된 100여 개 축소 유적, 자전거·카트 투어',
    goKo: 'BTS 케하역에서 택시 또는 송태우로 약 10분',
    lat: 13.543, lon: 100.636, tag: 'AncientCity',
  },
  {
    id: 'lumpini', nameKo: '룸피니 공원', nameEn: 'Lumpini Park', nameTh: 'สวนลุมพินี',
    area: '실롬/사라댕',
    blurbKo: '도심의 거대한 초록 허파. 아침저녁으로 방콕 사람들의 쉼터예요.',
    seeKo: '호수 보트, 야자수 길, 유유히 다니는 왕도마뱀',
    goKo: 'MRT 룸피니역 또는 실롬역, BTS 살라댕역과도 가까워요',
    lat: 13.7307, lon: 100.5418, tag: 'Lumpini',
  },
  {
    id: 'benjakitti', nameKo: '벤짜낏 포레스트파크', nameEn: 'Benjakitti Forest Park', nameTh: 'สวนป่าเบญจกิติ',
    area: '아속/클롱토이',
    blurbKo: '옛 담배공장 부지를 숲과 습지로 되살린 도심 속 자연.',
    seeKo: '나무 사이를 잇는 스카이워크, 호수 데크, 도심 스카이라인 뷰',
    goKo: 'MRT 시리킷 국립컨벤션센터역에서 바로',
    lat: 13.7234, lon: 100.5601, tag: 'Benjakitti',
  },
  {
    id: 'chatuchak-market', nameKo: '짜뚜짝 주말시장', nameEn: 'Chatuchak Weekend Market', nameTh: 'ตลาดนัดจตุจักร',
    area: '짜뚜짝',
    blurbKo: '주말이면 수천 개 상점이 열리는 세계적인 거대 시장.',
    seeKo: '의류·앤티크·수공예·식물까지 거의 모든 것, 미로 같은 골목',
    goKo: 'MRT 깜팽펫역 또는 짜뚜짝공원역, BTS 모칫역. 주말에만 풀 오픈',
    lat: 13.7999, lon: 100.5503, tag: 'Chatuchak',
  },
  {
    id: 'or-tor-kor', nameKo: '어떠꺼 시장', nameEn: 'Or Tor Kor Market', nameTh: 'ตลาด อ.ต.ก.',
    area: '짜뚜짝',
    blurbKo: '세계 최고 수준으로 꼽히는 깔끔한 청과·식재료 시장.',
    seeKo: '산처럼 쌓인 열대 과일, 향신료·말린 식재료, 화려한 두리안',
    goKo: 'MRT 깜팽펫역 3번 출구 바로 앞',
    lat: 13.805, lon: 100.549, tag: 'OrTorKor',
  },
  {
    id: 'flower-market', nameKo: '빡크롱 꽃시장', nameEn: 'Pak Khlong Talat (Flower Market)', nameTh: 'ปากคลองตลาด',
    area: '올드타운 강변',
    blurbKo: '밤에 더 화려해지는, 24시간 돌아가는 방콕 최대 꽃시장.',
    seeKo: '메리골드·재스민·장미 다발의 색과 향, 분주한 새벽 도매 풍경',
    goKo: 'MRT 사남차이역에서 도보 약 5분',
    lat: 13.7407, lon: 100.4969, tag: 'FlowerMarket',
  },
  {
    id: 'yaowarat', nameKo: '야오와랏(차이나타운)', nameEn: 'Yaowarat (Chinatown)', nameTh: 'เยาวราช',
    area: '삼판타웡',
    blurbKo: '해 질 녘 네온이 켜지면 거리 전체가 살아나는 차이나타운.',
    seeKo: '금은방 거리, 거대한 한자 간판과 네온, 골목 노점 풍경',
    goKo: 'MRT 왓망꼰역에서 도보 바로',
    lat: 13.7404, lon: 100.5104, tag: 'Yaowarat',
  },
  {
    id: 'talat-noi', nameKo: '딸랏너이', nameEn: 'Talat Noi', nameTh: 'ตลาดน้อย',
    area: '차이나타운 강변',
    blurbKo: '낡은 정비소와 벽화가 어우러진, 사진가들의 골목 동네.',
    seeKo: '구석구석 스트리트 아트, 오래된 중국식 가옥과 사당, 강변 카페',
    goKo: 'MRT 후아람퐁역에서 도보 약 10분',
    lat: 13.735, lon: 100.513, tag: 'TalatNoi',
  },
  {
    id: 'phahurat', nameKo: '파후랏(리틀 인디아)', nameEn: 'Phahurat (Little India)', nameTh: 'พาหุรัด',
    area: '차이나타운 인근',
    blurbKo: '차이나타운 옆에 숨은 작은 인도. 직물과 향신료의 거리.',
    seeKo: '화려한 사리 원단 가게, 인도·시크 사원, 향신료 골목',
    goKo: 'MRT 삼욧역에서 도보 약 10분',
    lat: 13.746, lon: 100.499, tag: 'Phahurat',
  },
  {
    id: 'asiatique', nameKo: '아시아티크 더 리버프론트', nameEn: 'Asiatique The Riverfront', nameTh: 'เอเชียทีค เดอะ ริเวอร์ฟร้อนท์',
    area: '짜런끄룽 강변',
    blurbKo: '옛 항만 창고를 개조한 강변 야시장. 저녁 산책에 딱.',
    seeKo: '대관람차, 강바람 부는 산책로, 창고형 상점과 공연',
    goKo: 'BTS 사판탁신역 사톤 선착장에서 무료 셔틀보트(저녁 운행)',
    lat: 13.7045, lon: 100.5095, tag: 'Asiatique',
  },
  {
    id: 'iconsiam', nameKo: '아이콘시암', nameEn: 'ICONSIAM', nameTh: 'ไอคอนสยาม',
    area: '톤부리 강변',
    blurbKo: '강변에 우뚝 선 초대형 복합몰. 실내에 수상시장을 통째로 옮겨놨어요.',
    seeKo: '실내 수상시장 슥시암, 강을 따라 펼쳐지는 분수쇼, 전망 좋은 강변',
    goKo: 'BTS 골드라인 짜런나콘역, 또는 사톤 선착장에서 셔틀보트(유료)',
    lat: 13.7263, lon: 100.51, tag: 'IconSiam',
  },
  {
    id: 'mahanakhon', nameKo: '마하나콘 스카이워크', nameEn: 'Mahanakhon SkyWalk', nameTh: 'มหานคร สกายวอล์ค',
    area: '실롬',
    blurbKo: '방콕에서 가장 높은 옥상 전망대. 유리바닥 위에 서보세요.',
    seeKo: '314m 옥상 전망, 아찔한 유리 바닥, 360도 도시 파노라마',
    goKo: 'BTS 청논시역과 바로 연결',
    lat: 13.7232, lon: 100.5285, tag: 'Mahanakhon',
  },
  {
    id: 'baiyoke', nameKo: '바이욕 스카이 타워', nameEn: 'Baiyoke Sky Tower', nameTh: 'ใบหยกสกาย',
    area: '쁘라뚜남',
    blurbKo: '한때 태국에서 가장 높았던 빌딩의 회전 전망대.',
    seeKo: '84층 회전 전망 플로어, 쁘라뚜남 시장이 한눈에',
    goKo: 'BTS 랏차테위역에서 도보, 또는 쁘라뚜남 일대에서 택시',
    lat: 13.754, lon: 100.54, tag: 'Baiyoke',
  },
  {
    id: 'khaosan', nameKo: '카오산 로드', nameEn: 'Khao San Road', nameTh: 'ถนนข้าวสาร',
    area: '방람푸',
    blurbKo: '전 세계 배낭여행자가 모이는 방콕의 전설적인 거리.',
    seeKo: '밤새 북적이는 노점과 거리 공연, 올드타운으로 이어지는 골목',
    goKo: '가까운 전철역은 없어요. MRT 삼욧역에서 택시·도보, 또는 강변 보트 프라아팃 선착장',
    lat: 13.7588, lon: 100.4977, tag: 'KhaoSan',
  },
  {
    id: 'phra-sumen', nameKo: '프라수멘 요새 & 산티차이쁘라깐 공원', nameEn: 'Phra Sumen Fort & Santichaiprakan Park', nameTh: 'ป้อมพระสุเมรุ',
    area: '방람푸 강변',
    blurbKo: '옛 성벽의 흔적이 남은, 강바람 시원한 작은 강변 공원.',
    seeKo: '하얀 옛 요새, 강을 마주한 잔디밭과 큰 나무, 일몰 명소',
    goKo: '카오산 로드에서 도보 약 5분, 프라아팃 선착장 인근',
    lat: 13.7626, lon: 100.4955, tag: 'PhraSumen',
  },
  {
    id: 'chaophraya-boat', nameKo: '짜오프라야 강 보트', nameEn: 'Chao Phraya Express Boat', nameTh: 'เรือด่วนเจ้าพระยา',
    area: '강변',
    blurbKo: '현지인의 출퇴근길이자 가장 저렴한 강변 관광. 한 번은 타봐야 해요.',
    seeKo: '강에서 올려다보는 왓 아룬·왕궁·대교들, 시원한 강바람',
    goKo: 'BTS 사판탁신역 사톤(중앙) 선착장에서 승선, 오렌지 깃발 보트가 무난',
    lat: 13.7187, lon: 100.5096, tag: 'ChaoPhraya',
  },
  {
    id: 'skypark', nameKo: '짜오프라야 스카이파크', nameEn: 'Chao Phraya Sky Park', nameTh: 'สวนลอยฟ้าเจ้าพระยา',
    area: '강변',
    blurbKo: '버려진 다리를 공원으로 되살린, 강 위를 걷는 산책로.',
    seeKo: '강을 가로지르는 보행 전용 다리, 양쪽 강변 전망과 일몰',
    goKo: 'MRT 사남차이역에서 도보, 또는 강 건너 톤부리 쪽 접근',
    lat: 13.725, lon: 100.494, tag: 'SkyPark',
  },
  {
    id: 'rama8-bridge', nameKo: '라마 8세 다리', nameEn: 'Rama VIII Bridge', nameTh: 'สะพานพระราม ๘',
    area: '강변',
    blurbKo: '한쪽 기둥만으로 상판을 잡아당기는 우아한 비대칭 사장교.',
    seeKo: '노란 케이블의 사장교, 다리 아래 강변 공원, 야경 명소',
    goKo: '방람푸·두싯 쪽 강변, 택시가 편해요',
    lat: 13.766, lon: 100.497, tag: 'Rama8',
  },
  {
    id: 'bang-krachao', nameKo: '방까쩌(방콕의 허파)', nameEn: 'Bang Krachao', nameTh: 'บางกะเจ้า',
    area: '프라쁘라댕',
    blurbKo: '강이 휘감은 초록 섬. 자전거로 정글 같은 도심 탈출.',
    seeKo: '나무 터널 자전거길, 스리나콘 케안 칸 공원, 주말 방남픙 수상시장',
    goKo: '클롱토이/방나 인근 선착장에서 도선으로 강 건너 + 자전거 대여',
    lat: 13.69, lon: 100.556, tag: 'BangKrachao',
  },
  {
    id: 'siam', nameKo: '시암 스퀘어 & 파라곤', nameEn: 'Siam Square & Paragon', nameTh: 'สยามสแควร์',
    area: '빠툼완',
    blurbKo: '방콕 쇼핑·트렌드의 심장. 젊은 거리와 럭셔리몰이 한자리에.',
    seeKo: '시암스퀘어 거리 문화, 시암 파라곤·센터의 대형 쇼핑',
    goKo: 'BTS 시암역과 바로 연결(수쿰윗·실롬 라인 환승역)',
    lat: 13.746, lon: 100.534, tag: 'Siam',
  },
  {
    id: 'sealife', nameKo: '씨라이프 방콕 오션월드', nameEn: 'SEA LIFE Bangkok Ocean World', nameTh: 'ซีไลฟ์ แบงคอก โอเชี่ยน เวิลด์',
    area: '빠툼완',
    blurbKo: '시암 파라곤 지하에 숨은 동남아 최대급 수족관.',
    seeKo: '바닷속을 걷는 유리 터널, 상어·펭귄·가오리, 수중 쇼',
    goKo: 'BTS 시암역, 시암 파라곤 지하(B1~B2)',
    lat: 13.7462, lon: 100.5343, tag: 'SeaLife',
  },
  {
    id: 'terminal21', nameKo: '터미널 21', nameEn: 'Terminal 21', nameTh: 'เทอร์มินอล 21',
    area: '아속',
    blurbKo: '층마다 세계 도시를 테마로 꾸민, 구경만 해도 즐거운 몰.',
    seeKo: '파리·런던·도쿄 등 도시 테마 층, 인증샷 명소인 테마 화장실',
    goKo: 'BTS 아속역·MRT 수쿰윗역과 바로 연결',
    lat: 13.7374, lon: 100.5601, tag: 'Terminal21',
  },
  {
    id: 'lhong1919', nameKo: '롱 1919', nameEn: 'Lhong 1919', nameTh: 'ล้ง 1919',
    area: '톤부리 강변',
    blurbKo: '백 년 넘은 중국식 항구 저택. 지금은 상점보다 헤리티지 건축과 사당이 중심이에요.',
    seeKo: 'ㄷ자형 중국식 건물과 벽화, 바닷길의 수호신 마조 사당, 한적한 강변',
    goKo: 'ICONSIAM 인근(끄롱산), 택시 또는 셔틀보트. 상업시설은 축소된 상태라 방문 전 운영 확인 권장',
    lat: 13.7343, lon: 100.5076, tag: 'Lhong1919',
  },
  {
    id: 'jam-factory', nameKo: '잼 팩토리', nameEn: 'The Jam Factory', nameTh: 'เดอะแจมแฟคทอรี่',
    area: '끄롱산 강변',
    blurbKo: '옛 창고를 개조한 강변 복합문화공간. 느긋한 오후에 어울려요.',
    seeKo: '갤러리와 디자인 서점, 큰 나무가 있는 안뜰, 강변 산책',
    goKo: 'ICONSIAM 인근(끄롱산), 사톤 선착장 셔틀보트 또는 택시',
    lat: 13.727, lon: 100.508, tag: 'JamFactory',
  },
  {
    id: 'snake-farm', nameKo: '스네이크 팜(적십자 뱀 농장)', nameEn: 'Queen Saovabha Snake Farm', nameTh: 'สถานเสาวภา',
    area: '실롬/빠툼완',
    blurbKo: '독사 연구소가 운영하는, 의외로 알찬 도심 속 뱀 농장.',
    seeKo: '독액 채취 시연과 뱀 핸들링 쇼, 다양한 독사 전시',
    goKo: 'MRT 삼얀역 또는 실롬역에서 도보(평일 위주 운영)',
    lat: 13.732, lon: 100.536, tag: 'SnakeFarm',
  },
  {
    id: 'wang-lang', nameKo: '왕랑 시장', nameEn: 'Wang Lang Market', nameTh: 'ตลาดวังหลัง',
    area: '톤부리(시리랏)',
    blurbKo: '현지 학생·직장인으로 북적이는 강변 패션·길거리 시장.',
    seeKo: '저렴한 의류와 잡화, 활기찬 강변 골목, 시리랏 의학박물관도 인근',
    goKo: '왕랑(시리랏) 선착장에서 바로, 강 건너 따창 선착장에서 도선',
    lat: 13.759, lon: 100.486, tag: 'WangLang',
  },
  {
    id: 'taling-chan', nameKo: '딸링찬 수상시장', nameEn: 'Taling Chan Floating Market', nameTh: 'ตลาดน้ำตลิ่งชัน',
    area: '톤부리(딸링찬)',
    blurbKo: '시내에서 가장 가까운 주말 수상시장. 운하 보트 투어가 인기.',
    seeKo: '운하 위 보트 좌판, 물가 평상, 운하를 도는 롱테일 보트 투어',
    goKo: '주말에만 열려요. 택시 또는 차량 추천',
    lat: 13.779, lon: 100.456, tag: 'TalingChan',
  },
  {
    id: 'lat-mayom', nameKo: '클롱 랏 마욤 수상시장', nameEn: 'Khlong Lat Mayom Floating Market', nameTh: 'ตลาดน้ำคลองลัดมะยม',
    area: '톤부리(딸링찬)',
    blurbKo: '관광지 티가 덜 나는, 현지인이 즐겨 찾는 주말 수상시장.',
    seeKo: '운하변 좌판과 정원, 보트 투어, 한적한 주말 동네 풍경',
    goKo: '주말에만 열려요. MRT 방쿤논역에서 무료 셔틀버스, 또는 택시',
    lat: 13.7619, lon: 100.4156, tag: 'LatMayom',
  },
  {
    id: 'safari-world', nameKo: '사파리 월드', nameEn: 'Safari World', nameTh: 'ซาฟารีเวิลด์',
    area: '민부리(방콕 외곽 동부)',
    blurbKo: '차로 사파리를 도는 방콕 최대 동물 테마파크. 가족 나들이에 좋아요.',
    seeKo: '차창 밖 사자·기린·얼룩말, 마린파크 돌고래·물개 쇼',
    goKo: '시내에서 멀어요. 택시 또는 차량으로 약 40~60분',
    lat: 13.865, lon: 100.703, tag: 'SafariWorld',
  },
  {
    id: 'dream-world', nameKo: '드림월드', nameEn: 'Dream World', nameTh: 'ดรีมเวิลด์',
    area: '빠툼타니(방콕 외곽 북부)',
    blurbKo: '아기자기한 테마와 놀이기구가 가득한 외곽 놀이공원.',
    seeKo: '스노우타운, 동화 같은 테마 정원, 다양한 놀이기구',
    goKo: '시내에서 멀어요. 택시 또는 차량으로 약 40~60분',
    lat: 13.9909, lon: 100.6752, tag: 'DreamWorld',
  },
] as const;

/** Pick today's place (rotates through the set by day of year, in array order). */
export function pickPlace(dtSeconds: number): Place {
  return pickByDay(PLACES, dtSeconds);
}
